services:
  - type: web
    name: admin-clone-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    plan: free
    region: oregon
